language: rust
env:
  global:
    - secure: CLHUG7GEOO1lb8ekE5YZf8eTCOAvR7VLIP2gpS6qm0dyp1uyghw8LOthKpHBJ6m12vDCW3pc/JA2tnTpacXWMVPfQ7Rgp61otFL3Eru+grLfIdth6yEtinShMZMFVljWoT7ARUl7SKHWCn4SRqdhCB6aTqiPp+glF7+H5IPTfJY=
script:
  - cargo test
  - cargo doc --no-deps
after_script:
  - mv target/doc .
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
