[package]
name = "r2d2"
version = "0.0.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A generic connection pool"

[lib]
name = "r2d2"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"
