[package]
name = "r2d2"
version = "0.5.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A generic connection pool"
repository = "https://github.com/sfackler/r2d2"
documentation = "https://sfackler.github.io/r2d2/doc/r2d2"
readme = "README.md"
keywords = ["database", "pool"]

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
log = "0.3"
time = "0.1.14"
